version: '3'

networks:
  car_network:
    driver: bridge

services:
  can_bridge:
    build: ./can_bridge
    container_name: can_bridge
    networks:
      - car_network
    privileged: true
    restart: unless-stopped
    volumes:
      - ./can_bridge:/app
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep bridge | grep -v grep || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 10
  
  infotainment:
    build: ./infotainment
    container_name: infotainment_ecu
    networks:
      - car_network
    privileged: true
    restart: unless-stopped
    volumes:
      - ./infotainment:/app
    depends_on:
      can_bridge:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "1337:1337"
  engine:
    build: ./engine
    container_name: engine_ecu
    networks:
      - car_network
    privileged: true
    restart: unless-stopped
    volumes:
      - ./engine:/app
    depends_on:
      can_bridge:
        condition: service_healthy
  can_monitor:
    build: ./can_monitor
    container_name: can_monitor
    networks:
      - car_network
    volumes:
      - ./can_monitor:/app
    tty: true
    stdin_open: true